services:
  # ---------- Python tiles / gribapi ----------
  gribapi:
    container_name: paint-gribapi
    build:
      context: ./paint-tiles/dockerfiles/gribapi
    volumes:
      - ${GRIBAPI_PUBLIC}:/gribapi/public
      - ${GRIBAPI_LOGS}:/gribapi/logs
      - ${GRIBAPI_SRC}:/gribapi
    environment:
      - PARAMS=${PARAMS}
    restart: unless-stopped

  # ---------- Backend (Node.js) ----------
  backend:
    container_name: paint-backend
    build:
      context: ./paint-nodejs
      args:
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=production
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - gribapi
    restart: unless-stopped
    volumes:
      - ${GALLERY_PATH}:./gallary
      - ${IMAGES_PATH}:./images
  # ---------- Frontend (Next.js) ----------
  frontend:
    container_name: paint-frontend
    build:
      context: ./paint-nextjs
      args:
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_HTTP_URL=${NEXT_PUBLIC_BACKEND_HTTP_URL}
      - NEXT_PUBLIC_BACKEND_WS_URL=${NEXT_PUBLIC_BACKEND_WS_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    restart: unless-stopped
